# -*- coding: utf-8 -*-
"""creditcard_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABwXaxN0WVXh8nxjgSSc_B4OZDucNFYt
"""

import pandas as pd
df=pd.read_csv('/content/dim_customers.csv')
df.head(20)

fact=pd.read_csv('/content/fact_spends.csv')

fact

data=pd.merge(df,fact,on="customer_id", how="inner")

data

data.to_csv("data.csv",index=False)

data.groupby("category")["spend"].sum().sort_values(ascending=False)

data.groupby("city")["spend"].sum().sort_values(ascending=False)

data.groupby("age_group")["spend"].sum()

data.groupby(["age_group","city"])["spend"].sum()

top_customers=data.groupby("customer_id")["spend"].sum().sort_values(ascending=False)
top_20_percent=top_customers.head(int(len(top_customers)*0.2))
top_20_percent

customer_summ=data.groupby("customer_id").agg({"spend":"sum","avg_income":"mean"})
customer_summ["spend_ratio"]=customer_summ["spend"]/customer_summ["avg_income"]

customer_summ["spend_ratio"]

def segment(row):
  if row["avg_income"]>70000 and row["spend"]>50000:
    return "High Value"
  elif row["avg_income"]>40000:
    return "Medium Value"
  else:
    return "Low Value"
customer_summ["segment"]=customer_summ.apply(segment,axis=1)
customer_summ["segment"]

data.groupby("payment_type")["spend"].sum().sort_values(ascending=False)

data.groupby("month")["spend"].sum()

final_data=data.groupby("customer_id").agg({
    "spend":"sum",
    "avg_income":"mean",
    "age_group":"first",
    "city":"first",
    "gender":"first",}).reset_index()
final_data["spend_ratio"]=final_data["spend"]/final_data["avg_income"]

final_data.to_csv("final_data.csv",index=False)

